// Account fixture definitions and generation logic.

import type { AccountSeed } from './types';

/**
 * Deterministic account fixtures for compatibility testing.
 * These mirror the Firefly-III account structure and cover the core account types.
 */
export const SEED_ACCOUNTS: AccountSeed[] = [
  {
    name: 'Default Account',
    type: 'asset',
    currency_code: 'JPY',
    active: true,
    include_net_worth: true,
    current_balance: '100000.00',
    account_role: 'default-account',
    iban: null,
    bic: null,
    account_number: null,
    notes: 'Primary checking account for compatibility tests',
    liability_type: null,
    liability_direction: null,
    interest: null,
    interest_period: null,
  },
  {
    name: 'Savings Account',
    type: 'asset',
    currency_code: 'JPY',
    active: true,
    include_net_worth: true,
    current_balance: '500000.00',
    account_role: 'savings',
    iban: null,
    bic: null,
    account_number: null,
    notes: 'High-yield savings',
    liability_type: null,
    liability_direction: null,
    interest: '0.005',
    interest_period: 'monthly',
  },
  {
    name: 'Cash Account',
    type: 'cash',
    currency_code: 'JPY',
    active: true,
    include_net_worth: true,
    current_balance: '15000.00',
    account_role: null,
    iban: null,
    bic: null,
    account_number: null,
    notes: null,
    liability_type: null,
    liability_direction: null,
    interest: null,
    interest_period: null,
  },
  {
    name: 'Expense Account',
    type: 'expense',
    currency_code: 'JPY',
    active: true,
    include_net_worth: false,
    current_balance: '0.00',
    account_role: null,
    iban: null,
    bic: null,
    account_number: null,
    notes: 'Groceries and daily expenses',
    liability_type: null,
    liability_direction: null,
    interest: null,
    interest_period: null,
  },
  {
    name: 'Revenue Account',
    type: 'revenue',
    currency_code: 'JPY',
    active: true,
    include_net_worth: false,
    current_balance: '0.00',
    account_role: null,
    iban: null,
    bic: null,
    account_number: null,
    notes: 'Salary income',
    liability_type: null,
    liability_direction: null,
    interest: null,
    interest_period: null,
  },
  {
    name: 'Credit Card',
    type: 'liability',
    currency_code: 'JPY',
    active: true,
    include_net_worth: true,
    current_balance: '-25000.00',
    account_role: null,
    iban: null,
    bic: null,
    account_number: null,
    notes: 'Primary credit card',
    liability_type: 'credit card',
    liability_direction: null,
    interest: '0.199',
    interest_period: 'monthly',
  },
];
